version: '2'
services:
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  kafka-container:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
  redis-container:
    image: redis
    ports:
      - "6379"
    restart: always
